### ISSUE TITLE
Override PagerExtension::path

### ISSUE THREAD

**Issue by goseyn** [makerlabs/PagerBundle#12]
I would like to add query string support to generate the url in the Pager Twig Extension class.
How can i do to override PagerExtension::path ?

services.xml :

```
<parameter key="makerlabs.twig.extension.pager.class">MakerLabs\PagerBundle\Twig\Extension\PagerExtension</parameter>
```

MakerLabs\PagerBundle\Twig\Extension\PagerExtension::path :

<pre><code>
public function path($route, $page, array $parameters = array())
{
    ...
    
---    return $this->router->generate($route, $parameters);
+++    $query = '';
+++    if (isset($parameters['_query_string'])) {
+++        $query = $parameters['_query_string'];
+++
+++        unset($parameters['_query_string']);
+++    }
+++
+++    return $this->router->generate($route, $parameters) . $query;
}
</code></pre>

**Comment by makerlabs** [comment]
You don't need to override the path to do that. Just look at the Customization -> Passing additional parameters to the pager links in https://github.com/makerlabs/PagerBundle/wiki. If you won't provide the 'type' parameter in your route definition symfony will simply append them as query_string parameters.

**Comment by miguel-mx** [comment]
Could you provide an example please? I am trying too to append a query string with multiple parameters  to the paginate function.

Thank you in advance.

**Comment by makerlabs** [comment]
As I said before you must only pass additional parameters... Simply define your query string parameters as an array in your controller:

``` php
$parameters = array(
   'name1' => 'value',
   'name2' => 'value', //etc
);
```

and then pass them to your twig or php template:

Twig:

```
{{ paginate(pager, 'route_name', parameters) }}
```

PHP:

``` php
<?php echo $view['pager']->paginate($pager, 'example_route', $parameters) ?>
```

any additional parameters are automatically appended as query string or as a part of your route url if you include them in the pattern.

**Comment by miguel-mx** [comment]
Thank you for your response, I was looking more for something like this:

{{ path(route, args) ~ '?' ~ app.request.queryString }}

I'm gonna use it as you suggest.

Thank you.
