### ISSUE TITLE
Add to Packagist repository

### ISSUE THREAD

**Issue by rvanlaak** [makerlabs/PagerBundle#18]
I can't find your bundle in the default Composer repo 

https://packagist.org/search/?q=pagerbundle

**Comment by aosmialowski** [comment]
@Rvanlaak The package is already on Packagist, you need to search for pager-bundle instead of pagerbundle ;)

https://packagist.org/packages/makerlabs/pager-bundle

**Comment by rvanlaak** [comment]
Damn indeed :) You might want to add some extra info to the README.md

**Comment by aosmialowski** [comment]
@makerlabs Ping. Do you mind adding such info to the README.md?

**Comment by smoya** [comment]
The owner of the repository did not reply. I had to create a fork and added the package in packagist long ago. https://packagist.org/packages/makerlabs/pager-bundle.
