### ISSUE TITLE
infinite paging

### ISSUE THREAD

**Issue by rosscdh** [makerlabs/PagerBundle#9]
hi there,

first of all great work, finally php is starting to make coding almost as fun as those djangonauts have in their pockets! ;)

I am considering forking and creating a new adapter based on the doctrine adapter that allows for endless pagination al la: http://pypi.python.org/pypi/django-endless-pagination

are there any plans for this? or shall I go ahead and make the fork/branch?

regards
RCdH

**Comment by makerlabs** [comment]
Actually I don't have enough time to improve it (maybe some minor update of unit test but nothing more ;)) so any help would be appreciated ;)

**Comment by rosscdh** [comment]
Sure, ill let you know when something develops :) next few weeks as Im pretty overloaded atm :) but good work mate :)

**Comment by makerlabs** [comment]
Thx. So keep me posted and happy coding :>

**Comment by rosscdh** [comment]
Started a basic infinite paging Pager "InfinitePager" implementation as well as infinipage twig and php helpers :)
